basePath: /api
definitions:
  model.Error:
    properties:
      error: {}
    type: object
  model.Response:
    properties:
      body: {}
    type: object
host: 127.0.0.1:8084
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: EDUCRM back calendar server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TCRA API
  version: "1.0"
paths:
  /oauth:
    post:
      consumes:
      - application/json
      description: Sets teacher's OAUTH2Token
      operationId: SetOAUTH2Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: internal server error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Sets teacher's OAUTH2Token
      tags:
      - Calendar
swagger: "2.0"
